version: "2"
linters:
  enable:
    - gosec
    - misspell
    - prealloc
    - staticcheck
    - unconvert
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/malvex/vibediff
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
