repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-vet
      #- id: go-imports
      #- id: go-cyclo
      #  args: [-over=15]
      - id: golangci-lint
      - id: go-mod-tidy

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.32.0
    hooks:
      - id: eslint
        # types: [text] is a workaround - default types: [javascript] doesn't match .ts/.tsx files
        types: [text]
        files: ^web/.*\.(js|jsx|ts|tsx)$
        args: ['--config=web/eslint.config.js']
        additional_dependencies:
          - eslint@9.32.0
          - '@eslint/js@9.32.0'
          - 'typescript-eslint@8.38.0'
          - 'typescript@5.8.3'
          - 'eslint-plugin-react-hooks@5.2.0'
          - 'eslint-plugin-react-refresh@0.4.20'
          - 'globals@16.3.0'
